# Generated by Django 4.1.6 on 2023-02-09 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MoveOn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThePupil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('starting_weight', models.FloatField()),
                ('height', models.FloatField()),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoveOn.trainer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
