# Generated by Django 4.1.6 on 2023-02-09 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MoveOn', '0003_exercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('number', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')])),
            ],
        ),
        migrations.CreateModel(
            name='PlanExercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoveOn.exercise')),
                ('training_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoveOn.daynumber')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(null=True)),
                ('status', models.IntegerField(choices=[(1, 'active'), (2, 'to do'), (3, 'ended')])),
                ('start_date', models.DateField()),
                ('week_training_days', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')])),
                ('exercises', models.ManyToManyField(through='MoveOn.PlanExercises', to='MoveOn.exercise')),
                ('the_pupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoveOn.thepupil')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoveOn.trainer')),
            ],
        ),
        migrations.AddField(
            model_name='planexercises',
            name='training_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoveOn.trainingplan'),
        ),
        migrations.CreateModel(
            name='ActualWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_weight', models.FloatField()),
                ('add_date', models.DateField()),
                ('the_pupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoveOn.thepupil')),
            ],
        ),
    ]
