# Generated by Django 4.1.6 on 2023-02-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoveOn', '0004_daynumber_planexercises_trainingplan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingplan',
            name='status',
            field=models.IntegerField(choices=[(1, 'active'), (2, 'to do'), (3, 'ended')], default=2),
        ),
    ]
