# Generated by Django 4.1.6 on 2023-02-20 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MoveOn', '0005_alter_trainingplan_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsMatched',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.IntegerField(choices=[(1, 'Left'), (2, 'Right')])),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoveOn.thepupil')),
                ('rated_pupil', models.ManyToManyField(related_name='rated_one', to='MoveOn.thepupil')),
            ],
        ),
    ]
