# Generated by Django 4.1.6 on 2023-02-20 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MoveOn', '0006_ismatched'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ismatched',
            name='rated_pupil',
        ),
        migrations.AddField(
            model_name='ismatched',
            name='rated_pupil',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='rated_one', to='MoveOn.thepupil'),
            preserve_default=False,
        ),
    ]
