# Generated by Django 4.1.6 on 2023-02-20 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MoveOn', '0009_alter_ismatched_rated_pupil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ismatched',
            name='rated_pupil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rated_one', to='MoveOn.thepupil'),
        ),
        migrations.AlterUniqueTogether(
            name='ismatched',
            unique_together={('pupil', 'rated_pupil')},
        ),
    ]
