# Generated by Django 4.1.6 on 2023-02-23 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MoveOn', '0014_alter_actualweight_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyAchievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('which_series', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('result', models.FloatField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoveOn.planexercises')),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoveOn.thepupil')),
            ],
        ),
    ]
