# Generated by Django 4.1.6 on 2023-02-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoveOn', '0015_myachievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='myachievements',
            name='add_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='myachievements',
            name='date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actualweight',
            name='add_date',
            field=models.DateField(auto_now=True),
        ),
    ]
