# Generated by Django 4.1.6 on 2023-02-24 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MoveOn', '0016_myachievements_add_date_myachievements_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='myachievements',
            unique_together={('which_series', 'exercise', 'date')},
        ),
    ]
