# Generated by Django 4.1.6 on 2023-02-25 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MoveOn', '0017_alter_myachievements_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='myachievements',
            name='training_plan',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='MoveOn.trainingplan'),
            preserve_default=False,
        ),
    ]
